### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by dimboknv** [go-pkgz/repeater#1]
I seems to find memory leak in Fixed Delay strategy but it may be in others.

if use shorted delay that repeats fun execution time then publisher routine will have locked on sending to signals channel.

maybe should use select for send.
```
select {
case <-ctx.Done():
	return
case ch <- struct{}{}:
	sleep(ctx, s.Delay)
}
```
instead 

https://github.com/go-pkgz/repeater/blob/3d06550c83496689aee032a66d1969135f2971a3/strategy/fixed.go#L25-L31

```
func TestRepeaterMemoryLeak(t *testing.T) {
	unit := func(amout int) time.Duration {
		return time.Duration(amout) * 10 * time.Millisecond
	}

	leak := func() error {
		ctx, cancel := context.WithTimeout(context.Background(), unit(3))
		defer cancel()
		err := NewDefault(3, unit(1)).Do(ctx, func() error {
			time.Sleep(unit(2))

			select {
			case <-ctx.Done():
				return nil
			default:
				return fmt.Errorf("some err")
			}
		})
		return err
	}

	before := runtime.NumGoroutine()
	num := []int{}
	for i := 0; i <= 25; i++ {
		leak()
		num = append(num, runtime.NumGoroutine())
	}
	after := runtime.NumGoroutine()
	require.False(t, after > before, "looks like you have goroutines leak: %+v", num)
}
```

**Comment by umputun** [comment]
thx for the report. I have moved send to select but left sleep outside of select, just in case to prevent a busy loop. Converted your code to pair of tests and, to me, it looks like the issue is fixed.

**Comment by dimboknv** [comment]
thx for quick fix
